typography_spectrum: 0.5
color:
  brandColors:
    - '#fae9c8'
    - '#0e327b'
    - '#197fa6'
    - '#25cfb3'
    - '#fa759f'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5
analytics:
  google: null
  facebook: null
  twitter: null
name: Grid Style Sheets
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - id: twitter.com/d4tocchini
    url: twitter.com/d4tocchini
    name: Twitter
    type: external
  - id: 127674eb-03c0-497b-8aed-9755c0f6e8c0
    url: 2016-04-23-this-is-a-wonderful-life.html
    name: This is a wonderful life
    type: content
favicon: null
purpose: []
